action_id: trunk-cache-prune
date: 2024-11-17 14:58:10
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-cache-prune'. See .trunk\out\NEKao.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\NEKao.yaml
timestamp: 1731855490
full_timestamp:
  nanos: 532868000
  seconds: 1731855490
trunk_version: 1.22.8
