action_id: trunk-cache-prune
date: 2024-11-17 17:49:19
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-cache-prune'. See .trunk\out\6X7eF.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\6X7eF.yaml
timestamp: 1731865759
full_timestamp:
  nanos: 768874000
  seconds: 1731865759
trunk_version: 1.22.8
