action_id: trunk-cache-prune
date: 2024-11-21 19:21:47
run: trunk cache prune --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-cache-prune'. See .trunk\out\O5Oha.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\O5Oha.yaml
timestamp: 1732216907
full_timestamp:
  nanos: 387660000
  seconds: 1732216907
trunk_version: 1.22.8
