action_id: trunk-whoami
date: 2024-11-16 09:20:08
run: trunk whoami
run_from: ""
trigger: schedule 24h+1h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-whoami'. See .trunk\out\ohio3.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\ohio3.yaml
timestamp: 1731748808
full_timestamp:
  nanos: 552480000
  seconds: 1731748808
trunk_version: 1.22.8
