action_id: trunk-share-with-everyone
date: 2024-11-21 19:28:44
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\cEbpW.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\cEbpW.yaml
timestamp: 1732217324
full_timestamp:
  nanos: 362738000
  seconds: 1732217324
trunk_version: 1.22.8
