action_id: trunk-share-with-everyone
date: 2024-11-17 14:58:17
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: schedule 24h
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\hhajR.yaml for details.
  error_path: C:\Users\holna\Pylearning\goit-cs-hw-02\.trunk\out\hhajR.yaml
timestamp: 1731855497
full_timestamp:
  nanos: 914981000
  seconds: 1731855497
trunk_version: 1.22.8
